name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: 'generate report'
      run: |
        pip install coverage
        pip install numpy
        pip install scipy
        pip install plotly
        pip install mkdocs-material
        pip install mkdocstrings
        pip install mkdocstrings
        pip install pytkdocs 
        pip install mkdocs-jupyter
        pip install mkdocs-meta-descriptions-plugin
        pip install jupyter_contrib_nbextensions
        coverage run -m unittest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true